apiVersion: v1
kind: Namespace
metadata:
  name: "user-test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: "user-test"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: "user-test"
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - name: mariadb
          image: mariadb:10.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rahasia"
            - name: MYSQL_DATABASE
              value: "nextcloud"
            - name: MYSQL_USER
              value: "nextcloud"
            - name: MYSQL_PASSWORD
              value: "nextcloud"
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: "user-test"
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  namespace: "user-test"
spec:
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:apache
          ports:
            - containerPort: 80
          env:
            - name: MYSQL_HOST
              value: "mariadb"
            - name: MYSQL_DATABASE
              value: "nextcloud"
            - name: MYSQL_USER
              value: "nextcloud"
            - name: MYSQL_PASSWORD
              value: "nextcloud"
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-storage
      volumes:
        - name: nextcloud-storage
          persistentVolumeClaim:
            claimName: nextcloud-data
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
  namespace: "user-test"
spec:
  type: NodePort
  selector:
    app: nextcloud
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30050
